global:
  provider: aks
  environment: prod

cilium:
  aksByoCni: false

ingressNginx:
  enabled: true
  helmValues:
    controller:
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

certManager:
  enabled: true

externalSecrets:
  enabled: false
  azureKeyVault:
      vaultUrl: https://your-vault-name.vault.azure.net
      tenantId: your-azure-tenant-id
      authType: WorkloadIdentity   # AKS with managed identity
      # authType: ServicePrincipal  # DOKS or any non-AKS cluster

caddyGateway:
  hostname: turnkey.gov.stellarbridge.app

doppler:
  config: prod

otel:
  elasticEndpoint: https://elastic.gov.internal:4317
