# Install after Tekton Pipelines. Pin versions with pipeline when upgrading.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.31.0/release.yaml
