{{- if and .Values.tekton.enabled .Values.tekton.triggers.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: turnkey-tekton-triggers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repoUrl | quote }}
    targetRevision: {{ .Values.argocd.targetRevision | quote }}
    path: deploy/tekton-triggers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
{{- end }}
