config:
  cluster.provider: doks
  cluster.provisionMode: managed
  cluster.name: turnkey-dev
  cluster.region: nyc1
  cluster.version: 1.35.1-do.0
  cluster.nodeCount: "1"
  cluster.nodeSize: s-1vcpu-2gb
  cluster.env: dev
  cluster.kubeconfig: ""
  argocd.repoUrl: https://github.com/EpykLab/turnkey
  argocd.targetRevision: master
  argocd.path: bootstrap
  doppler.project: stellarbridge
  doppler.config: dev
  otel.elasticEndpoint: https://elastic.internal:4317
