apiVersion: v1
kind: Service
metadata:
  name: turnkey-status-page
  namespace: turnkey-status
  labels:
    app.kubernetes.io/name: turnkey-status-page
    app.kubernetes.io/component: status-page
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: turnkey-status-page
  ports:
    - name: http
      port: 80
      targetPort: http
