{{- if .Values.cilium.enabled }}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  version: 1.16.5
  targetNamespace: kube-system
  valuesContent: |-
    kubeProxyReplacement: {{ .Values.cilium.kubeProxyReplacement }}
    hubble:
      enabled: {{ .Values.cilium.hubble.enabled }}
{{- end }}
