{{- if .Values.kyverno.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Privileged containers are not allowed."
        pattern:
          spec:
            containers:
              - securityContext:
                  privileged: false
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources-and-probes
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-requests-and-limits
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "CPU/memory requests and limits are required."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"
    - name: require-readiness-and-liveness
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "readinessProbe and livenessProbe are required."
        pattern:
          spec:
            containers:
              - livenessProbe: {}
                readinessProbe: {}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: image-hygiene
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  validationFailureAction: {{ .Values.kyverno.policyMode.imageDigestPinning }}
  background: true
  rules:
    - name: no-latest-tag
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "Using :latest is not allowed."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
{{- end }}
