{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.onePassword.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
  annotations:
    argocd.argoproj.io/sync-wave: "13"  # after ESO installs at wave 12
    turnkey.io/change-control: {{ .Values.argocd.repoUrl | quote }}
spec:
  provider:
    onepassword:
      connectHost: {{ .Values.externalSecrets.onePassword.connectHost | quote }}
      vaults:
        {{ .Values.externalSecrets.onePassword.vaultName }}: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: {{ .Values.externalSecrets.onePassword.authSecretName }}
            namespace: {{ .Values.externalSecrets.namespace }}
            key: token
{{- end }}
